### PR TITLE
add local_score_BIC_from_cov

### PR DESCRIPTION
**Pull request by wean2016**
### Description section
1. add local_score_BIC_from_cov
2. set the default bic score function in GES.py with local_score_BIC_from_cov

### Test plan section
python -m unittest TestGES.py # should pass
image

### CODE REVIEW

**Comment by tofuwen** [comment]
Could you update your description to be more informative? It can provide reviewers more context.

In the description, it's better to indicate why we need this change, what is this change supposed to do, the benefits of this new functionality. :)

**Comment by tofuwen** [comment]
Hmm, we need a better design for this PR and in general LocalScoreClass. We should arrange a meeting to talk about the design. The current way is not extensible --- in the near future, it would be super difficult to maintain.

Some general suggestions when writing code:
1. you should try to avoid copy and paste code (or never do it). I noticed that, the code in your new function is basically the same as previous function --- you should try to reuse code.
2. Think about how to re-use other part of the code in the codebase --- I am not 100% sure, but is it possible to combine LocalScoreClass with CIT class in some way? It seems to me they are doing similar thing: using data to calculate something, and cache / cov matrix should be re-used. cc @MarkDana So let's have a joint meeting to discuss.

**Comment by kunwuz** [comment]
> Hmm, we need a better design for this PR and in general LocalScoreClass. We should arrange a meeting to talk about the design. The current way is not extensible --- in the near future, it would be super difficult to maintain.
> 
> Some general suggestions when writing code:
> 
>     1. you should try to avoid copy and paste code (or never do it). I noticed that, the code in your new function is basically the same as previous function --- you should try to reuse code.
> 
>     2. Think about how to re-use other part of the code in the codebase --- I am not 100% sure, but is it possible to combine LocalScoreClass with CIT class in some way? It seems to me they are doing similar thing: using data to calculate something, and cache / cov matrix should be re-used. cc @MarkDana So let's have a joint meeting to discuss.

Thanks for the great suggestions! Yes, I totally agree with you that the score function, as long as many other modules, should be refactored as previously mentioned.

At the same time, it might also be necessary to first make some critical/quick changes that benefit the algorithms a lot. For example, in this PR, we could directly use the covariance matrix as the input to avoid repeat computation, which should be included ASAP to improve the performance. But of course, we should never forget to refactor afterward for maintainability and further changes :)

**Comment by tofuwen** [comment]
yeah, @kunwuz is right.

@wean2016, when you have time, we can book a meeting and I can share with you some general coding principles which may help you write code in the future. :) We can use this PR as an example.

**Comment by wean2016** [comment]
> yeah, @kunwuz is right.
> 
> @wean2016, when you have time, we can book a meeting and I can share with you some general coding principles which may help you write code in the future. :) We can use this PR as an example.

Thank you very much for your suggestions, I think you are very right. We should write better-designed code. Also, I've been catching up on my paper lately and I'm a bit busy. Could we wait for the AAAI submission to finish before we meet about this topic?

**Comment by wean2016** [comment]
> @wean2016 Sure, this sounds reasonable.
> 
> Could you add a todo (and assign the todo to you) in the code (format: # @todo (your name)) to remind us to refactor after you have more time? Then I think we can push this PR first to at least unblock our users. :)

Yes, I agree with your opinions. I add some # todo in the score function file. Then, this change may remind us in the future.

**Comment by MarkDana** [comment]
> Hmm, we need a better design for this PR and in general LocalScoreClass. We should arrange a meeting to talk about the design. The current way is not extensible --- in the near future, it would be super difficult to maintain.
> 
> Some general suggestions when writing code:
> 
> 1. you should try to avoid copy and paste code (or never do it). I noticed that, the code in your new function is basically the same as previous function --- you should try to reuse code.
> 2. Think about how to re-use other part of the code in the codebase --- I am not 100% sure, but is it possible to combine LocalScoreClass with CIT class in some way? It seems to me they are doing similar thing: using data to calculate something, and cache / cov matrix should be re-used. cc @MarkDana So let's have a joint meeting to discuss.

Sure! Happy to discuss :)

**Comment by tofuwen** [comment]
Sure, looks good. I think we can merge this PR for now. @kunwuz

**Pull request merged**
